### ISSUE TITLE
Locally configured BIMserver cannot load console

### ISSUE THREAD

**Issue by siriuszyx** [opensourceBIM/Console#2]
Hi,

We configured a BIMserver locally on our machine, BIMserver 1.5.125 by Tomcat 8.5 on Windows Server 2016. We know we haven't got some settings correct so not all functionalities are working right now.

The console when you go in, cannot see any modules on the left; and cannot load any codes in the examples sections.
![1](https://user-images.githubusercontent.com/31344240/53076681-36c11480-352b-11e9-9c28-09aba729eba8.jpg)
![2](https://user-images.githubusercontent.com/31344240/53076687-39bc0500-352b-11e9-938a-44bdcb11b1c9.jpg)

But the bimvie.ws is mostly working well, can checkin model and see...
But cannot reset password. The email server is set up, can send password reset email, new revision email etc...When click on reset button it will prompt this.
![3](https://user-images.githubusercontent.com/31344240/53076960-edbd9000-352b-11e9-88bf-4002c6f1f322.jpg)
We talked about this issue (console abnormal) to Léon, and he suggested we raise an issue here.

**Comment by rubendel** [comment]
I see a non-local address in the address bar on the top-right, are you trying to connect to that server? Because I wouldn't call that local.

**Comment by siriuszyx** [comment]
> I see a non-local address in the address bar on the top-right, are you trying to connect to that server? Because I wouldn't call that local.

Of course not, the domain is not configured yet. We access by the IP address of the server in our company LAN. The server is connected to Internet. We tried to turn off the Windows Firewall on the server completely and the abovementioned issues persist.

**Comment by rubendel** [comment]
Hmm the latest Console build did not run successfully, it contained a fix specifically for finding the BIMserver address, so that might be the problem. A new build (0.0.32) of Console is online, you can update it using BIMvie.ws, or reinstall and the new one will be fetched automatically (BIMserver 1.5.125).

**Comment by rubendel** [comment]
Just tested with 1.5.125, and it seems to work now, please reopen if not.

**Comment by siriuszyx** [comment]
![image](https://user-images.githubusercontent.com/31344240/53138941-f6ad7080-35c2-11e9-80ce-77a91b36a31c.png)

The latest console I can see is 0.31. I'll try to install the whole .war package and let you know

**Comment by siriuszyx** [comment]
I removed the old .war package and the directory in ```/webapps```, and tried to install bimserverwar-1.5.125.war again. But now it is constantly stuck at the "Loading..." page and can't continue to install.

It's possible to access on the server either by localhost or IP address, but on other computers in the LAN will just show the page of Microsoft Internet Information Services. Am I getting something wrong?
